name: Go

on:
  push:
    branches: [ main, 'release-*' ]
    tags: [ '*' ]
  pull_request:
    branches: [ main, 'release-*' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://github.com
    steps:

      - name: Chekcout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3.3.0
        with:
          go-version: 1.17

      - name: Setup signing key
        run: |
          mkdir enclave-config
          echo "$PRIVATE_KEY_PEM" > enclave-config/privatekey.pem
          sha256sum enclave-config/privatekey.pem
        shell: bash
        env:
          PRIVATE_KEY_PEM: ${{ secrets.PRIVATE_KEY_PEM }}

      - name: Login to the container registry
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build
        run: make docker-build
        env:
          IMG_TAG: ${{ github.ref_name }}
      - name: push
        run: make docker-push
        env:
          IMG_TAG: ${{ github.ref_name }}
 