name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Chekcout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3.3.0
        with:
          go-version: 1.17
          cache: true

      - name: Setup signing key
        run: |
          mkdir enclave-config
          echo "$PRIVATE_KEY_PEM" > enclave-config/privatekey.pem
          sha256sum enclave-config/privatekey.pem
          echo ${{secrets.PRIVATE_KEY_PEM}} > enclave-config/privatekey.pem
          sha256sum enclave-config/privatekey.pem
        shell: bash
        env:
          PRIVATE_KEY_PEM: ${{secrets.PRIVATE_KEY_PEM}}

      - name: Login to the container registry
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build
        run: make docker-build
      - name: push
        run: make docker-push
 