name: TAG

on:
  push:
    branches: [ main, 'release-*' ]
    tags: [ '*' ]
  pull_request:
    branches: [ main, 'release-*' ]
  tags:
    - '*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TAG: ${{ github.base_ref || github.ref_name }} 

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://github.com
    steps:
      - name: Chekcout code
        uses: actions/checkout@v3
      - name: Login to the container registry
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build
        run: make docker-build
        env:
          IMG_TAG: ${{ env.TAG }}
      - name: push
        run: make docker-push
        env:
          IMG_TAG: ${{ env.TAG }}
 